### ISSUE TITLE
Adding `isFrontPage` boolean to Pages data

### ISSUE THREAD

**Issue by zgordon** [wp-graphql/gatsby-wpgraphql-blog-example#5]
It would be helpful to know if a page is assigned as the static homepage from WordPress.  If we could expose this then we could tell when calling createPage() when to reassign the URI from the slug in WordPress to `/` so it loads as the homepage in Gatsby automatically as well.

**Comment by samuelgoddard** [comment]
Hey @zgordon did you manage to get this working? Would love to see an example, struggling to get this working myself with a custom blog / home page setup on WP

**Comment by zgordon** [comment]
Haven't had a chance to make any updates to this in a while as we're focused on our new premium themes coming out, but how to do this is covered in my Headless WordPress Course with Gatsby over at javascriptforwp.com :)

**Comment by jasonbahl** [comment]
@samuelgoddard this issue was actually intended to be opened on the WPGraphQL repo, and @zgordon did open it there: https://github.com/wp-graphql/wp-graphql/issues/1028

You can now query the `isFrontPage` field on Pages in the WPGraphQL Schema, but there's not an example of that implemented in Gatsby that I can point you too right now.

**Comment by zgordon** [comment]
Here is an example for those looking :)

https://github.com/zgordon/gatsby-wordpress-course/blob/da58358693d5ab086291b867c2b0ad6447a614e4/gatsby-wordpress/gatsby/createPages.js#L56

**Comment by samuelgoddard** [comment]
Thank you very much @zgordon @jasonbahl, exactly what I was after. Keep up the great work! :)
