### ISSUE TITLE
Getting errors on build

### ISSUE THREAD

**Issue by kosvrouvas** [wp-graphql/gatsby-wpgraphql-blog-example#6]
Hi, I'm getting multiple errors when `gatsby build` (also on netlify)

`  WebpackError: TypeError: Cannot read property 'name' of null

  - index.js:17 PostEntryMeta
    src/components/PostEntryMeta/index.js:13:40`

Removing Meta altogether I get the next error:

`Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=object&args[]= for the full message or use the non-minified dev environment for full errors and ad  ditional helpful warnings.`

This is without changing anything to the repo (I'm using the demo site as a source), tried to update every npm package but still nothing.

**Comment by justinwhall** [comment]
I have not run a test but what happens when you just comment out [this line](https://github.com/wp-graphql/gatsby-wpgraphql-blog-example/blob/master/src/components/PostEntryMeta/index.js#L17)

Also, you might want to try a fresh install using the current package.lock. Upgrading would be great but it could also introduce additional conflicts.

**Comment by kosvrouvas** [comment]
Removing it i get 

`Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=object&args[]= for the full message or use the non-minified dev environment for full errors and ad ditional helpful warnings.`
